name: Deploy to GCP Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: mannequin-segmenter
  REGION: europe-west4
  GAR_LOCATION: europe-west4-docker.pkg.dev
  REPOSITORY: mannequin-segmenter-repo

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker ${{ env.GAR_LOCATION }}

    - name: Build CPU-optimized Docker image
      run: |
        docker build -f Dockerfile -t ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker build -f Dockerfile -t ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:latest .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        docker push ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:latest

    - name: Deploy to Cloud Run with CPU (20 instances)
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --port 5001 \
          --memory 4Gi \
          --cpu 2 \
          --timeout 900 \
          --cpu-boost \
          --concurrency=1 \
          --min-instances 5 \
          --max-instances 20 \
          --execution-environment gen2 \
          --set-env-vars="ENVIRONMENT=production,PYTHONPATH=/app,FORCE_CPU=true,PORT=5001" \
          --set-secrets="AWS_ACCESS_KEY_ID=aws-access-key:latest" \
          --set-secrets="AWS_SECRET_ACCESS_KEY=aws-secret-key:latest" \
          --set-secrets="AWS_S3_BUCKET_NAME=aws-s3-bucket:latest" \
          --set-secrets="AWS_S3_REGION=aws-s3-region:latest"

    - name: Route traffic to latest revision
      run: |
        echo "🔄 Routing 100% traffic to latest revision..."
        gcloud run services update-traffic ${{ env.SERVICE_NAME }} \
          --region ${{ env.REGION }} \
          --to-latest

    - name: Set public access
      run: |
        gcloud run services add-iam-policy-binding ${{ env.SERVICE_NAME }} \
          --region=${{ env.REGION }} \
          --member="allUsers" \
          --role="roles/run.invoker" || echo "Public access may be restricted by organization policy"

    - name: Get Cloud Run URL
      run: |
        SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} --platform managed --region ${{ env.REGION }} --format 'value(status.url)')
        echo "🚀 Service deployed to: $SERVICE_URL"
        echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV

    - name: Verify deployment
      run: |
        echo "🧪 Verifying service is running..."
        gcloud run services describe ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --format="value(status.conditions[0].status)"
        echo "✅ Service verification completed!"

    - name: Deployment Summary
      run: |
        echo "## 🎉 Deployment Successful!" >> $GITHUB_STEP_SUMMARY
        echo "- **Service**: ${{ env.SERVICE_NAME }}" >> $GITHUB_STEP_SUMMARY
        echo "- **URL**: ${{ env.SERVICE_URL }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Region**: ${{ env.REGION }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Image**: ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Auto-scaling**: 5-20 instances (1 concurrent per instance)" >> $GITHUB_STEP_SUMMARY
        echo "- **Memory**: 4Gi per instance" >> $GITHUB_STEP_SUMMARY
        echo "- **CPU**: 2 per instance" >> $GITHUB_STEP_SUMMARY
        echo "- **Total capacity**: 20 parallel requests" >> $GITHUB_STEP_SUMMARY 
